### PR TITLE
#1 docs: add apps folder and set .env file

### PR DESCRIPTION
**Pull request by KangPeiHsuan**
1. add apps folder
2. update .env.example file

### CODE REVIEW

**Review by toshi0809 — APPROVED** [review]
good job!

**Comment by jaychen1007** [comment]
nice

**Review by Roger-0227 — APPROVED** [review]
ＯＫ

**Comment by Liu-Che-Ming** [comment]
OK

**Review by Liu-Che-Ming — APPROVED** [review]

**Review by jaychen1007 — APPROVED** [review]

**Pull request merged**
